Elcodi\ProductBundle\Entity\Product:
    type: entity
    repositoryClass: Elcodi\ProductBundle\Repository\ProductRepository
    table: product
    fields:
        name:
            column: name
            type: string
            length: 255
            nullable: false
        sku:
            column: sku
            type: string
            length: 255
            nullable: true
        slug:
            column: slug
            type: string
            length: 255
            nullable: false
        shortDescription:
            column: short_description
            type: string
            length: 255
            nullable: true
        description:
            column: description
            type: text
            nullable: true
        showInHome:
            column: show_in_home
            type: boolean
            nullable: true
        dimensions:
            column: dimensions
            type: string
            length: 255
            nullable: true
        stock:
            column: stock
            type: integer
            nullable: true
        price:
            column: price
            type: integer
            nullable: true
        reducedPrice:
            column: reduced_price
            type: integer
            nullable: true
        metaTitle:
            column: meta_title
            type: string
            length: 255
            nullable: true
        metaDescription:
            column: meta_description
            type: string
            length: 255
            nullable: true
        metaKeywords:
            column: meta_keywords
            type: string
            length: 255
            nullable: true
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        enabled:
            column: enabled
            type: boolean

    manyToOne:
        manufacturer:
            targetEntity: Elcodi\ProductBundle\Entity\Interfaces\ManufacturerInterface
            inversedBy: products
            joinColumn:
                name: manufacturer_id
                referencedColumnName: id
                nullable: true
        principalVariant:
            targetEntity: Elcodi\ProductBundle\Entity\Interfaces\VariantInterface
            joinColumn:
                name: principal_variant_id
                referencedColumnName: id
                nullable: true
        principalCategory:
            targetEntity: Elcodi\ProductBundle\Entity\Interfaces\CategoryInterface
            joinColumn:
                name: principal_category_id
                referencedColumnName: id
                nullable: true
        principalImage:
            targetEntity: Elcodi\MediaBundle\Entity\Interfaces\ImageInterface
            joinColumn:
                name: principal_image_id
                referencedColumnName: id
                nullable: true
        priceCurrency:
            targetEntity: Elcodi\CurrencyBundle\Entity\Interfaces\CurrencyInterface
            joinColumn:
                 name: price_currency_id
                 referencedColumnName: id
                 nullable: true
        reducedPriceCurrency:
            targetEntity: Elcodi\CurrencyBundle\Entity\Interfaces\CurrencyInterface
            joinColumn:
                 name: reduced_price_currency_id
                 referencedColumnName: id
                 nullable: true

    oneToMany:
        variants:
            targetEntity: Elcodi\ProductBundle\Entity\Interfaces\VariantInterface
            mappedBy: product
            cascade: [ persist ]

    manyToMany:
        categories:
            targetEntity: Elcodi\ProductBundle\Entity\Interfaces\CategoryInterface
            inversedBy: products
            joinTable:
                name: product_category
                joinColumns:
                    product_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    category_id:
                        referencedColumnName: id
        images:
            targetEntity: Elcodi\MediaBundle\Entity\Interfaces\ImageInterface
            joinTable:
                name: product_image
                joinColumns:
                    product_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    image_id:
                        referencedColumnName: id
        attributes:
            targetEntity: Elcodi\AttributeBundle\Entity\Interfaces\AttributeInterface
            joinTable:
                name: product_attribute
                joinColumns:
                    product_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    attribute_id:
                        referencedColumnName: id

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
