services:

    #
    # Controllers
    #
    elcodi.controller.metric_input:
        class: Elcodi\Component\Metric\Input\Controller\InputController
        arguments:
            - '@request_stack'
            - '@elcodi.metric_manager'
            - '@elcodi.factory.datetime'
