language: php

env:
    - COMPOSER_OPTIONS="--prefer-source"

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - 7.0

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.0
    include:
        - php: 5.4
          env: COMPOSER_OPTIONS="--prefer-lowest"

before_install:
    - sh -c "sudo mkdir vendor"
    - sh -c "sudo mount -t tmpfs -o size=512M tmpfs vendor"

install:
    - composer update --no-interaction ${COMPOSER_OPTIONS}

before_script:
    - sh -c "sudo mkdir /tmp/Elcodi"
    - sh -c "sudo mount -t tmpfs -o size=512M tmpfs /tmp/Elcodi/"

script:
  - bin/phpunit

notifications:
    email: false
