build: false
platform: x86
clone_folder: c:\projects\elcodi

matrix:
  fast_finish: true

cache:
  - '%LOCALAPPDATA%\Composer\files'

init:
  - SET PATH=C:\Program Files\OpenSSL;c:\tools\php;%PATH%

install:
  - cinst -y OpenSSL.Light
  - cinst -y php
  - cd c:\tools\php
  - copy php.ini-production php.ini /Y
  - echo extension_dir=ext >> php.ini
  - echo memory_limit=1G >> php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_gd2.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - echo extension=php_pdo_sqlite.dll >> php.ini
  - cd %APPVEYOR_BUILD_FOLDER%
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar config preferred-install source
  - IF %GH_TOKEN% php composer.phar config github-oauth.github.com %GH_TOKEN%
  - IF %GH_TOKEN% php composer.phar config preferred-install dist
  - php composer.phar install --no-interaction --no-progress

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - vendor\bin\phpunit.bat --verbose
