parameters:

    #
    # Factories
    #
    elcodi.core.currency.factory.abstract.abstract.class: Elcodi\Component\Currency\Factory\Abstracts\AbstractPurchasableFactory
    elcodi.core.currency.factory.currency.class: Elcodi\Component\Currency\Factory\CurrencyFactory
    elcodi.core.currency.factory.currency_exchange_rate.class: Elcodi\Component\Currency\Factory\CurrencyExchangeRateFactory

    #
    # Services
    #
    elcodi.core.currency.service.currency_manager.class: Elcodi\Component\Currency\Services\CurrencyManager
    elcodi.core.currency.service.currency_converter.class: Elcodi\Component\Currency\Services\CurrencyConverter
    elcodi.core.currency.service.currency_session_manager.class: Elcodi\Component\Currency\Services\CurrencySessionManager
    elcodi.core.currency.populator.currency_rates_populator.class: Elcodi\Component\Currency\Populator\CurrencyExchangeRatesPopulator

    #
    # Providers
    #
    elcodi.core.currency.service.currency_exchange_rates_provider.class: Elcodi\Component\Currency\Services\CurrencyExchangeRatesProvider

    #
    # Twig extensions
    #
    elcodi.core.currency.twig_extension.print_money.class: Elcodi\Component\Currency\Twig\PrintMoneyExtension

    #
    # Wrappers
    #
    elcodi.core.currency.wrapper.currency.class: Elcodi\Component\Currency\Wrapper\CurrencyWrapper

    #
    # Commands
    #
    elcodi.core.currency.command.currency_exchange_rates_populate.class: Elcodi\Component\Currency\Command\CurrencyExchangeRatesPopulateCommand
