services:

    #
    # Commands
    #
    elcodi.command.populate_currency_rates:
        class: Elcodi\Component\Currency\Command\CurrencyExchangeRatesPopulateCommand
        arguments:
            - '@elcodi.populator.currency_exchange_rate'
        tags:
            -  { name: console.command }
