services:

    #
    # Factories
    #

    #
    # Factory for entity image
    #
    elcodi.factory.image:
        class: Elcodi\Component\Media\Factory\ImageFactory
        calls:
            - [setEntityNamespace, ["%elcodi.entity.image.class%"]]
            - [setDateTimeFactory, ["@elcodi.factory.datetime"]]
