services:

    #
    # Service
    #
    elcodi.manager.media_image:
        class: %elcodi.manager.media_image.class%
        arguments:
            - @elcodi.factory.image
            - @elcodi.manager.media_file
            - @elcodi.core.media.resize.default

    elcodi.manager.media_file:
        class: %elcodi.manager.media_file.class%
        arguments:
            - @elcodi.core.media.filesystem.default
            - @elcodi.transformer.media_file_identifier

    elcodi.image_uploader:
        class: %elcodi.image_uploader.class%
        arguments:
            - @elcodi.object_manager.image
            - @elcodi.manager.media_file
            - @elcodi.manager.media_image
            - @elcodi.event_dispatcher.media

    #
    # Resize
    #
    elcodi.core.media.resize.imagemagick:
        class: %elcodi.core.media.resize.imagemagick.class%
        arguments:
            - %elcodi.core.media.image_resize_converter_bin_path%
            - %elcodi.core.media.image_resize_converter_default_profile%

    #
    # Routes
    #
    elcodi.router.media_image_resize:
        class: %elcodi.router.media_image_resize.class%
        arguments:
            - %elcodi.core.media.image_resize_controller_route_name%
            - %elcodi.core.media.image_resize_controller_route%
        tags:
            - { name: routing.loader }

    elcodi.router.media_image_view:
        class: %elcodi.router.media_image_view.class%
        arguments:
            - %elcodi.core.media.image_view_controller_route_name%
            - %elcodi.core.media.image_view_controller_route%
        tags:
            - { name: routing.loader }

    elcodi.router.media_image_upload:
        class: %elcodi.router.media_image_upload.class%
        arguments:
            - %elcodi.core.media.image_upload_controller_route_name%
            - %elcodi.core.media.image_upload_controller_route%
        tags:
            - { name: routing.loader }
