services:

    #
    # Twig extensions
    #
    elcodi.twig_extension.media_image:
        class: Elcodi\Component\Media\Twig\ImageExtension
        arguments:
            - @router
            - %elcodi.core.media.image_resize_controller_route_name%
            - %elcodi.core.media.image_view_controller_route_name%
            - %elcodi.core.media.generated_route_host%
        tags:
            - { name: twig.extension }
