services:

    #
    # Directors
    #
    elcodi.director.store:
        class: Elcodi\Component\Core\Services\ObjectDirector
        lazy: true
        arguments:
            - '@elcodi.object_manager.store'
            - '@elcodi.repository.store'
            - '@elcodi.factory.store'
