services:

    #
    # Services
    #
    elcodi.store:
        class: Elcodi\Component\Store\Entity\Interfaces\StoreInterface
        factory:
            - @elcodi.wrapper.store
            - get

    elcodi.store_uses_stock:
        class: StdClass
        public: false
        factory:
            - @elcodi.store
            - getUseStock

    elcodi.store_tracker:
        class: StdClass
        public: false
        factory:
            - @elcodi.store
            - getTracker

    elcodi.store_address:
        class: %elcodi.entity.address.class%
        public: false
        factory:
            - @elcodi.store
            - getAddress

    elcodi.store_template_hash:
        class: StdClass
        public: false
        factory:
            - @elcodi.store
            - getTemplate

    elcodi.store_template:
        class: Elcodi\Component\Plugin\Entity\Plugin
        public: false
        factory:
            - @elcodi.repository.plugin
            - findOneBy
        arguments:
            - { hash: @elcodi.store_template_hash }

    elcodi.store_template_bundle:
        class: StdClass
        public: false
        factory:
            - @elcodi.store_template
            - getBundleName

    elcodi.store_default_language:
        class: Elcodi\Component\Language\Entity\Interfaces\LanguageInterface
        public: false
        factory:
            - @elcodi.store
            - getDefaultLanguage

    elcodi.store_default_language_iso:
        class: StdClass
        public: false
        factory:
            - @elcodi.store_default_language
            - getIso

    elcodi.store_routing_strategy:
        class: StdClass
        public: false
        factory:
            - @elcodi.store
            - getRoutingStrategy

    elcodi.store_default_currency:
        class: Elcodi\Component\Language\Entity\Interfaces\LanguageInterface
        public: false
        factory:
            - @elcodi.store
            - getDefaultCurrency
