Elcodi\Component\ReferralProgram\Entity\ReferralLine:
    type: entity
    repositoryClass: Elcodi\Component\ReferralProgram\Repository\ReferralLineRepository
    table: referral_line
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    uniqueConstraints:
        referrer_idx:
          columns: [ referralhash_id, invited_email ]

    fields:
        invitedEmail:
            column: invited_email
            type: string
            length: 255
            nullable: true
        invitedName:
            column: invited_name
            type: string
            length: 255
            nullable: true
        source:
            column: source
            type: string
            length: 255
            nullable: false
        referrerCouponUsed:
            column: referrer_coupon_used
            type: boolean
            nullable: false
        invitedCouponUsed:
            column: invited_coupon_used
            type: boolean
            nullable: false
        referrerType:
            column: referrer_type
            type: string
            length: 255
            nullable: false
        invitedType:
            column: invited_type
            type: string
            length: 255
            nullable: false
        closed:
            column: closed
            type: boolean
            nullable: false
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        enabled:
            column: enabled
            type: boolean

    manyToOne:
        invited:
            targetEntity: Elcodi\Component\User\Entity\Interfaces\CustomerInterface
            joinColumn:
                name: invited_id
                referencedColumnName: id
        referralHash:
            targetEntity: Elcodi\Component\ReferralProgram\Entity\Interfaces\ReferralHashInterface
            inversedBy: referralLines
            joinColumn:
                name: referralhash_id
                referencedColumnName: id
                nullable: false
        referralRule:
            targetEntity: Elcodi\Component\ReferralProgram\Entity\Interfaces\ReferralRuleInterface
            inversedBy: referralLines
            joinColumn:
                name: referralrule_id
                referencedColumnName: id
                nullable: false
        referrerCoupon:
            targetEntity: Elcodi\Component\Coupon\Entity\Interfaces\CouponInterface
            joinColumn:
                name: referrer_coupon_id
                referencedColumnName: id
                nullable: true
        referrerAssignedCoupon:
            targetEntity: Elcodi\Component\Coupon\Entity\Interfaces\CouponInterface
            joinColumn:
                name: referrer_assigned_coupon_id
                referencedColumnName: id
                nullable: true
        invitedCoupon:
            targetEntity: Elcodi\Component\Coupon\Entity\Interfaces\CouponInterface
            joinColumn:
                name: invited_coupon_id
                referencedColumnName: id
                nullable: true
        invitedAssignedCoupon:
            targetEntity: Elcodi\Component\Coupon\Entity\Interfaces\CouponInterface
            joinColumn:
                name: invited_assigned_coupon_id
                referencedColumnName: id
                nullable: true

    lifecycleCallbacks:
        preUpdate: [loadClosed, loadUpdateAt]
        prePersist: [loadClosed, loadUpdateAt]
