services:

    #
    # Services
    #
    elcodi.core.user.services.newsletter_manager:
        class: %elcodi.core.user.services.newsletter_manager.class%
        arguments:
            customer_wrapper: @elcodi.core.user.wrapper.customer_wrapper
            entity_manager: @doctrine.orm.entity_manager
            event_dispatcher: @event_dispatcher
            validator: @validator

    elcodi.core.user.services.password_manager:
        class: %elcodi.core.user.services.password_manager.class%
        arguments:
            entity_manager: @doctrine.orm.entity_manager
            router: @router
            event_dispatcher: @event_dispatcher
            recovery_hash_generator: @elcodi.core.user.generator.recover_hash

    elcodi.core.user.services.customer_manager:
        class: %elcodi.core.user.services.customer_manager.class%
        arguments:
            event_dispatcher: @event_dispatcher
            security_context: @?security.context

    elcodi.core.user.wrapper.customer_wrapper:
        class: %elcodi.core.user.wrapper.customer_wrapper.class%
        arguments:
            customer_repository: @=service("doctrine.orm.entity_manager").getRepository(parameter("elcodi.core.user.entity.customer.class"))
            entity_manager: @doctrine.orm.entity_manager
            session: @session
            customer_factory: @elcodi.core.user.factory.customer
            session_field_name: %elcodi.core.user.session_field_name%
            security_context: @?security.context

    #
    # Generators
    #
    elcodi.core.user.generator.recover_hash:
        class: %elcodi.core.user.generator.recover_hash.class%