parameters:

    database_driver: pdo_sqlite
    database_host: 127.0.0.1
    database_port: null
    database_name: elcodi
    database_user: root
    database_password: root
    database_path: database
    database_memory: false
    locale: es
    secret: keepcalmandengonga