Elcodi\Component\Product\Entity\Category:
    type: entity
    repositoryClass: Elcodi\Component\Product\Repository\CategoryRepository
    table: category
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        root:
            column: root
            type: boolean
            nullable: false
        position:
            column: position
            type: integer
            nullable: false
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        enabled:
            column: enabled
            type: boolean

    oneToMany:
        subCategories:
            targetEntity: Elcodi\Component\Product\Entity\Interfaces\CategoryInterface
            mappedBy: parent

    manyToOne:
        parent:
            targetEntity: Elcodi\Component\Product\Entity\Interfaces\CategoryInterface
            inversedBy: subCategories
            joinColumn:
                name: parent_id
                referencedColumnName: id
                nullable: true
                onDelete: "SET NULL"
                onUpdate: "CASCADE"

    manyToMany:
        products:
            targetEntity: Elcodi\Component\Product\Entity\Interfaces\ProductInterface
            mappedBy: categories

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
