Elcodi\Component\Product\Entity\Product:
    type: entity
    repositoryClass: Elcodi\Component\Product\Repository\ProductRepository
    table: product
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        sku:
            column: sku
            type: string
            length: 255
            nullable: true
        showInHome:
            column: show_in_home
            type: boolean
            nullable: true
        dimensions:
            column: dimensions
            type: string
            length: 255
            nullable: true
        stock:
            column: stock
            type: integer
            nullable: true
        price:
            column: price
            type: integer
            nullable: true
        reducedPrice:
            column: reduced_price
            type: integer
            nullable: true
        height:
            column: height
            type: integer
            nullable: false
        width:
            column: width
            type: integer
            nullable: false
        depth:
            column: depth
            type: integer
            nullable: false
        weight:
            column: weight
            type: integer
            nullable: false
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        enabled:
            column: enabled
            type: boolean

    manyToOne:
        manufacturer:
            targetEntity: Elcodi\Component\Product\Entity\Interfaces\ManufacturerInterface
            inversedBy: products
            joinColumn:
                name: manufacturer_id
                referencedColumnName: id
                nullable: true
        principalVariant:
            targetEntity: Elcodi\Component\Product\Entity\Interfaces\VariantInterface
            fetch: EAGER
            joinColumn:
                name: principal_variant_id
                referencedColumnName: id
                nullable: true
                onDelete: "SET NULL"
        principalCategory:
            targetEntity: Elcodi\Component\Product\Entity\Interfaces\CategoryInterface
            joinColumn:
                name: principal_category_id
                referencedColumnName: id
                nullable: true
        principalImage:
            targetEntity: Elcodi\Component\Media\Entity\Interfaces\ImageInterface
            joinColumn:
                name: principal_image_id
                referencedColumnName: id
                nullable: true
        priceCurrency:
            targetEntity: Elcodi\Component\Currency\Entity\Interfaces\CurrencyInterface
            joinColumn:
                 name: price_currency_id
                 referencedColumnName: id
                 nullable: true
        reducedPriceCurrency:
            targetEntity: Elcodi\Component\Currency\Entity\Interfaces\CurrencyInterface
            joinColumn:
                 name: reduced_price_currency_id
                 referencedColumnName: id
                 nullable: true

    oneToMany:
        variants:
            targetEntity: Elcodi\Component\Product\Entity\Interfaces\VariantInterface
            mappedBy: product
            cascade: [ "all" ]
            orphanRemoval: true

    manyToMany:
        categories:
            targetEntity: Elcodi\Component\Product\Entity\Interfaces\CategoryInterface
            inversedBy: products
            joinTable:
                name: product_category
                joinColumns:
                    product_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    category_id:
                        referencedColumnName: id
        images:
            targetEntity: Elcodi\Component\Media\Entity\Interfaces\ImageInterface
            joinTable:
                name: product_image
                joinColumns:
                    product_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    image_id:
                        referencedColumnName: id
        attributes:
            targetEntity: Elcodi\Component\Attribute\Entity\Interfaces\AttributeInterface
            joinTable:
                name: product_attribute
                joinColumns:
                    product_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"
                inverseJoinColumns:
                    attribute_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
