services:

    #
    # Managers
    #
    elcodi.manager.rule:
        class: Elcodi\Component\Rule\Services\RuleManager
        lazy: true
        arguments:
            - '@elcodi.expression_language'
            - '@elcodi.expression_language_context_collector'
