services:

    #
    # Event Listeners
    #
    elcodi.event_listener.entity_translator_entity:
        class: Elcodi\Component\EntityTranslator\EventListener\EntityTranslatorEntityEventListener
        lazy: true
        arguments:
            - '@service_container'
            - '@elcodi.locale'
        tags:
            - { name: doctrine.event_listener, event: postLoad }
