services:

    #
    # Commands
    #
    elcodi.command.translations_warmup:
        class: Elcodi\Component\EntityTranslator\Console\TranslationsWarmupCommand
        arguments:
            - '@elcodi.event_dispatcher.entity_translator'
