services:

    #
    # Event Dispatchers
    #
    elcodi.event_dispatcher.entity_translator:
        class: Elcodi\Component\EntityTranslator\EventDispatcher\EntityTranslatorEventDispatcher
        arguments:
            - '@event_dispatcher'
