services:

    #
    # Repositories
    #

    #
    # Repository for entity translation
    #
    elcodi.repository.entity_translation:
        parent: elcodi.abstract_repository
        class: Elcodi\Component\EntityTranslator\Repository\EntityTranslationRepository
        arguments:
            - %elcodi.entity.entity_translation.class%
