Elcodi\NewsletterBundle\Entity\NewsletterSubscription:
    type: entity
    repositoryClass: Elcodi\NewsletterBundle\Repository\NewsletterSubscriptionRepository
    table: newsletter_subscription
    fields:
        email:
            column: email
            type: string
            length: 255
            nullable: false
            unique: true
        hash:
            column: hash
            type: string
            length: 255
            nullable: false
            unique: true
        reason:
            column: reason
            type: text
            nullable: true
        createdAt:
            column: created_at
            type: datetime
            nullable: true
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
        enabled:
            column: enabled
            type: boolean

    manyToOne:
        language:
            targetEntity: Elcodi\LanguageBundle\Entity\Interfaces\LanguageInterface
            joinColumn:
                name: language_id
                referencedColumnName: id
                nullable: true

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
