parameters:

    #
    # Repositories
    #
    elcodi.core.configuration.repository.configuration.class: Elcodi\Component\Configuration\Repository\ConfigurationRepository

    #
    # Factories
    #
    elcodi.core.configuration.factory.configuration.class: Elcodi\Component\Configuration\Factory\ConfigurationFactory

    #
    # Services
    #
    elcodi.core.configuration.service.configuration_manager.class: Elcodi\Component\Configuration\Services\ConfigurationManager

    #
    # Twig extensions
    #
    elcodi.core.configuration.twig_extension.configuration_extension.class: Elcodi\Component\Configuration\Twig\ConfigurationExtension
