parameters:

    #
    # Factories
    #
    elcodi.factory.configuration.class: Elcodi\Component\Configuration\Factory\ConfigurationFactory

    #
    # Services
    #
    elcodi.manager.configuration.class: Elcodi\Component\Configuration\Services\ConfigurationManager

    #
    # Twig extensions
    #
    elcodi.twig_extension.configuration.class: Elcodi\Component\Configuration\Twig\ConfigurationExtension

    #
    # Commands
    #
    elcodi.configuration_set_command.class: Elcodi\Component\Configuration\Command\ConfigurationSetCommand
    elcodi.configuration_get_command.class: Elcodi\Component\Configuration\Command\ConfigurationGetCommand
