services:

    #
    # Factories
    #

    #
    # Factory for configuration entity
    #
    elcodi.factory.configuration:
        class: %elcodi.factory.configuration.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.configuration.entity.configuration.class%"]]
