services:

    #
    # Services
    #
    elcodi.manager.configuration:
        class: %elcodi.manager.configuration.class%
        lazy: true
        arguments:
            - @elcodi.object_manager.configuration
            - @elcodi.repository.configuration
            - @elcodi.factory.configuration
            - @elcodi.container_parameters
            - %elcodi.core.configuration.elements%
        calls:
            - [setCache, [@doctrine_cache.providers.elcodi_configurations]]
