services:

    #
    # Services
    #
    elcodi.configuration_manager:
        class: %elcodi.configuration_manager.class%
        arguments:
            configuration_object_manager: @elcodi.object_manager.configuration
            configuration_repository: @elcodi.repository.configuration
            configuration_factory: @elcodi.factory.configuration
            container_parameters: @elcodi.container_parameters
            configuration_elements: %elcodi.core.configuration.elements%
        calls:
            - [setCache, [@doctrine_cache.providers.elcodi_configurations]]
