services:

    #
    # Twig extensions
    #
    elcodi.twig_extension.configuration:
        class: Elcodi\Component\Configuration\Twig\ConfigurationExtension
        arguments:
            - '@elcodi.manager.configuration'
        tags:
            - { name: twig.extension }
