services:

    #
    # EventListeners
    #
    elcodi.event_dispatcher.comment:
        class: Elcodi\Component\Comment\EventDispatcher\CommentEventDispatcher
        arguments:
            - '@event_dispatcher'
