services:

    elcodi.event_listener.load_cart_prices:
        class: Elcodi\Component\Cart\EventListener\LoadCartPricesEventListener
        arguments:
            - '@elcodi.loader.cart_prices'
        tags:
            - { name: kernel.event_listener, event: cart.onload, method: loadCartPurchasablesAmount, priority: 16 }
            - { name: kernel.event_listener, event: cart.onload, method: loadCartTotalAmount, priority: 2 }

    elcodi.event_listener.save_cart:
        class: Elcodi\Component\Cart\EventListener\SaveCartEventListener
        arguments:
            - '@elcodi.cart_saver'
        tags:
            - { name: kernel.event_listener, event: cart.onload, method: saveCart, priority: 0 }

    elcodi.event_listener.validate_cart_integrity:
        class: Elcodi\Component\Cart\EventListener\ValidateCartIntegrityEventListener
        arguments:
            - '@elcodi.validator.cart_integrity'
        tags:
            - { name: kernel.event_listener, event: cart.preload, method: validateCartIntegrity, priority: 24 }

    elcodi.event_listener.validate_cart_amount:
        class: Elcodi\Component\Cart\EventListener\ValidateCartAmountEventListener
        arguments:
            - '@elcodi.validator.cart_amount'
        tags:
            - { name: kernel.event_listener, event: cart.onload, method: validateAmount, priority: 1 }

    elcodi.event_listener.update_stock_by_cart_line:
        class: Elcodi\Component\Cart\EventListener\UpdateStockByCartLineEventListener
        arguments:
            - '@elcodi.updater.cart_line_stock'
        tags:
            - { name: kernel.event_listener, event: order_line.oncreated, method: updatePurchasableStockByCartLine, priority: 0 }

    elcodi.event_listener.validate_empty_shipping_amount:
        class: Elcodi\Component\Cart\EventListener\ValidateEmptyShippingAmountEventListener
        arguments:
            - '@elcodi.validator.cart_shipping_method'
        tags:
            - { name: kernel.event_listener, event: cart.onload, method: validateEmptyShippingAmount, priority: 4 }

    elcodi.event_listener.save_cart_to_session:
        class: Elcodi\Component\Cart\EventListener\SaveCartToSessionEventListener
        arguments:
            - '@elcodi.session_manager.cart'
        tags:
            - { name: kernel.event_listener, event: cart.onload, method: saveCartInSession, priority: -2 }

    elcodi.event_listener.order_creation:
        class: Elcodi\Component\Cart\EventListener\OrderCreationEventListener
        arguments:
            - '@elcodi.object_manager.order'
            - '@elcodi.object_manager.cart'
        tags:
            - { name: kernel.event_listener, event: order.oncreated, method: saveOrder, priority: 0}
            - { name: kernel.event_listener, event: order.oncreated, method: setCartAsOrdered, priority: -16 }

    elcodi.event_listener.address_clone:
        class: Elcodi\Component\Cart\EventListener\AddressCloneEventListener
        arguments:
            - '@elcodi.repository.cart'
            - '@elcodi.object_manager.cart'
        tags:
            - { name: kernel.event_listener, event: address.onclone, method: updateCarts, priority: 0}
