services:

    #
    # Event Listeners
    #
    elcodi.core.cart.event_listener.cart:
        class: %elcodi.core.cart.event_listener.cart.class%
        arguments:
            cart_entity_manager: @elcodi.object_manager.cart
            cart_event_dispatcher: @elcodi.cart_event_dispatcher
            cart_manager: @elcodi.core.cart.service.cart_manager
            currency_wrapper: @elcodi.currency_wrapper
            currency_converter: @elcodi.currency_converter
        tags:
            - { name: kernel.event_listener, event: cart.preload, method: onCartPreLoad, priority: 0 }
            - { name: kernel.event_listener, event: cart.onload, method: onCartLoadPrices, priority: 16 }
            - { name: kernel.event_listener, event: cart.onload, method: onCartLoadFlush, priority: 0 }
            - { name: kernel.event_listener, event: cart.onload, method: onCartLoadQuantities, priority: -16 }
            - { name: kernel.event_listener, event: order.oncreated, method: onOrderCreated, priority: -16 }

    elcodi.core.cart.event_listener.order:
        class: %elcodi.core.cart.event_listener.order.class%
        arguments:
            order_entity_manager: @elcodi.object_manager.order
        tags:
            - { name: kernel.event_listener, event: order.oncreated, method: onOrderCreated, priority: 0}

    elcodi.core.cart.event_listener.order_state:
        class: %elcodi.core.cart.event_listener.order_state.class%
        arguments:
            order_entity_manager: @elcodi.object_manager.order
        tags:
            - { name: kernel.event_listener, event: order_state.onchange, method: onOrderStateOnChangeFlush, priority: 0 }

    elcodi.core.cart.event_listener.order_line_state:
        class: %elcodi.core.cart.event_listener.order_line_state.class%
        arguments:
            order_line_object_manager: @elcodi.object_manager.order_line
            order_state_event_dispatcher: @elcodi.order_state_event_dispatcher
            order_history_factory: @elcodi.core.cart.factory.order_history
        tags:
            - { name: kernel.event_listener, event: order_line_state.onchange, method: onOrderLineStateOnChange, priority: 16 }
            - { name: kernel.event_listener, event: order_line_state.onchange, method: onOrderLineStateOnChangeFlush, priority: 0 }

    elcodi.core.cart.event_listener.cart_session:
        class: %elcodi.core.cart.event_listener.cart_session.class%
        private: %elcodi.core.cart.session_field_name%
        arguments:
            cart_session_manager: @elcodi.cart_session_manager
        tags:
            - { name: kernel.event_listener, event: cart.onload, method: onCartLoad, priority: -2 }
