services:

    #
    # Factories
    #

    #
    # Factory for entity cart
    #
    elcodi.factory.cart:
        class: Elcodi\Component\Cart\Factory\CartFactory
        calls:
            - [setEntityNamespace, ["%elcodi.entity.cart.class%"]]
            - [setDateTimeFactory, ["@elcodi.factory.datetime"]]

    #
    # Factory for entity order
    #
    elcodi.factory.order:
        class: Elcodi\Component\Cart\Factory\OrderFactory
        arguments:
            - @elcodi.order_payment_states_machine_manager
            - @elcodi.order_shipping_states_machine_manager
            - @elcodi.wrapper.default_currency
        calls:
            - [setEntityNamespace, ["%elcodi.entity.order.class%"]]
            - [setDateTimeFactory, ["@elcodi.factory.datetime"]]

    #
    # Factory for entity cart_line
    #
    elcodi.factory.cart_line:
        class: Elcodi\Component\Cart\Factory\CartLineFactory
        calls:
            - [setEntityNamespace, ["%elcodi.entity.cart_line.class%"]]

    #
    # Factory for entity order_line
    #
    elcodi.factory.order_line:
        class: Elcodi\Component\Cart\Factory\OrderLineFactory
        calls:
            - [setEntityNamespace, ["%elcodi.entity.order_line.class%"]]
