services:

    #
    # Services
    #
    elcodi.manager.cart:
        class: Elcodi\Component\Cart\Services\CartManager
        arguments:
            - @elcodi.event_dispatcher.cart
            - @elcodi.event_dispatcher.cart_line
            - @elcodi.factory.cart
            - @elcodi.factory.cart_line

    elcodi.session_manager.cart:
        class: Elcodi\Component\Cart\Services\CartSessionManager
        arguments:
            - @session
            - %elcodi.cart_session_field_name%
            - %elcodi.cart_save_in_session%

    #
    # Wrappers
    #
    elcodi.wrapper.cart:
        class: Elcodi\Component\Cart\Wrapper\CartWrapper
        arguments:
            - @elcodi.event_dispatcher.cart
            - @elcodi.session_manager.cart
            - @elcodi.director.cart
            - @elcodi.wrapper.customer
