services:

    #
    # Services
    #
    elcodi.manager.cart:
        class: Elcodi\Component\Cart\Services\CartManager
        arguments:
            - '@elcodi.event_dispatcher.cart'
            - '@elcodi.event_dispatcher.cart_line'
            - '@elcodi.factory.cart'
            - '@elcodi.factory.cart_line'

    elcodi.session_manager.cart:
        class: Elcodi\Component\Cart\Services\CartSessionManager
        arguments:
            - '@session'
            - %elcodi.cart_session_field_name%
            - %elcodi.cart_save_in_session%

    elcodi.loader.cart_prices:
        class: Elcodi\Component\Cart\Services\CartPricesLoader
        arguments:
            - '@elcodi.wrapper.currency'
            - '@elcodi.converter.currency'

    elcodi.cart_saver:
        class: Elcodi\Component\Cart\Services\CartSaver
        arguments:
            - '@elcodi.object_manager.cart'

    elcodi.validator.cart_integrity:
        class: Elcodi\Component\Cart\Services\CartIntegrityValidator
        arguments:
            - '@elcodi.event_dispatcher.cart'
            - '@elcodi.stock_validator.purchasable'
            - '@elcodi.manager.cart'
            - '@?elcodi.store_uses_stock'

    elcodi.validator.cart_amount:
        class: Elcodi\Component\Cart\Services\CartAmountValidator

    elcodi.updater.cart_line_stock:
        class: Elcodi\Component\Cart\Services\CartLineStockUpdater
        arguments:
            - '@elcodi.stock_updater.purchasable'

    elcodi.validator.cart_shipping_method:
        class: Elcodi\Component\Cart\Services\CartShippingAmountValidator
        arguments:
            - '@elcodi.wrapper.empty_money'
