services:

    #
    # Transformers
    #
    elcodi.transformer.cart_order:
        class: Elcodi\Component\Cart\Transformer\CartOrderTransformer
        arguments:
            - '@elcodi.event_dispatcher.order'
            - '@elcodi.transformer.cart_line_order_line'
            - '@elcodi.factory.order'

    elcodi.transformer.cart_line_order_line:
        class: Elcodi\Component\Cart\Transformer\CartLineOrderLineTransformer
        arguments:
            - '@elcodi.event_dispatcher.order_line'
            - '@elcodi.factory.order_line'
