parameters:

    #
    # Factories
    #
    elcodi.core.geo.factory.country.class: Elcodi\Component\Geo\Factory\CountryFactory
    elcodi.core.geo.factory.state.class: Elcodi\Component\Geo\Factory\StateFactory
    elcodi.core.geo.factory.province.class: Elcodi\Component\Geo\Factory\ProvinceFactory
    elcodi.core.geo.factory.city.class: Elcodi\Component\Geo\Factory\CityFactory
    elcodi.core.geo.factory.postal_code.class: Elcodi\Component\Geo\Factory\PostalCodeFactory
    elcodi.core.geo.factory.address.class: Elcodi\Component\Geo\Factory\AddressFactory
    elcodi.core.geo.factory.zone.class: Elcodi\Component\Geo\Factory\ZoneFactory

    #
    # Commands
    #
    elcodi.core.geo.command.geo_populate.class: Elcodi\Component\Geo\Command\GeoPopulateCommand

    #
    # Services
    #
    elcodi.core.geo.populator.geo_populator.class: Elcodi\Component\Geo\Populator\GeoPopulator
    elcodi.core.geo.builder.geo_builder.class: Elcodi\Component\Geo\Builder\GeoBuilder
    elcodi.core.geo.service.zone_manager.class: Elcodi\Component\Geo\Services\ZoneManager
    elcodi.core.geo.service.zone_matcher.class: Elcodi\Component\Geo\Services\ZoneMatcher
    elcodi.core.geo.service.zone_finder.class: Elcodi\Component\Geo\Services\ZoneFinder

    #
    # GeoData populator adapters
    #
    elcodi.geo.dummy_populator_adapter.class: Elcodi\Component\Geo\Adapter\Populator\DummyPopulatorAdapter
    elcodi.geo.geodata_populator_adapter.class: Elcodi\Component\Geo\Adapter\Populator\GeoDataPopulatorAdapter
