services:

    #
    # Factories
    #

    #
    # Factory for entity address
    #
    elcodi.core.geo.factory.address:
        class: %elcodi.core.geo.factory.address.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.geo.entity.address.class%"]]

    elcodi.factory.address:
        alias: elcodi.core.geo.factory.address

    elcodi.core.geo.factory.state:
        class: %elcodi.core.geo.factory.state.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.geo.entity.state.class%"]]

    elcodi.factory.state:
        alias: elcodi.core.geo.factory.state

    elcodi.core.geo.factory.province:
        class: %elcodi.core.geo.factory.province.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.geo.entity.province.class%"]]

    elcodi.factory.province:
        alias: elcodi.core.geo.factory.province

    elcodi.core.geo.factory.city:
        class: %elcodi.core.geo.factory.city.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.geo.entity.city.class%"]]

    elcodi.factory.city:
        alias: elcodi.core.geo.factory.city

    elcodi.core.geo.factory.postal_code:
        class: %elcodi.core.geo.factory.postal_code.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.geo.entity.postal_code.class%"]]

    elcodi.factory.postal_code:
        alias: elcodi.core.geo.factory.postal_code

    elcodi.core.geo.factory.country:
        class: %elcodi.core.geo.factory.country.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.geo.entity.country.class%"]]

    elcodi.factory.country:
        alias: elcodi.core.geo.factory.country

    elcodi.core.geo.factory.zone:
        class: %elcodi.core.geo.factory.zone.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.geo.entity.zone.class%"]]

    elcodi.factory.zone:
        alias: elcodi.core.geo.factory.zone
