services:

    #
    # GeoData populator adapters
    #
    elcodi.location_populator:
        class: %elcodi.location_populator.geoname.class%
        synthetic: true

    elcodi.location_populator.geoname:
        class: %elcodi.location_populator.geoname.class%
        arguments:
            - @elcodi.extractor
            - @elcodi.location_builder

    #
    # Extractor
    #
    elcodi.extractor.directory:
        class: Mmoreram\Extractor\Filesystem\TemporaryDirectory
        public: false

    elcodi.extractor.extension_resolver:
        class: Mmoreram\Extractor\Resolver\ExtensionResolver
        public: false

    elcodi.extractor:
        class: Mmoreram\Extractor\Extractor
        arguments:
            - @elcodi.extractor.directory
            - @elcodi.extractor.extension_resolver
