services:

    #
    # GeoData populator adapters
    #
    elcodi.location_populator:
        class: Elcodi\Component\Geo\Populator\Adapters\GeonamesPopulatorAdapter
        synthetic: true

    elcodi.location_populator.geoname:
        class: Elcodi\Component\Geo\Populator\Adapters\GeonamesPopulatorAdapter
        arguments:
            - @elcodi.extractor
            - @elcodi.location_builder
            - @elcodi.factory.datetime

    #
    # Extractor
    #
    elcodi.extractor.directory:
        class: Mmoreram\Extractor\Filesystem\TemporaryDirectory
        public: false

    elcodi.extractor.extension_resolver:
        class: Mmoreram\Extractor\Resolver\ExtensionResolver
        public: false

    elcodi.extractor:
        class: Mmoreram\Extractor\Extractor
        arguments:
            - @elcodi.extractor.directory
            - @elcodi.extractor.extension_resolver
