parameters:

    #
    # Location api version
    #
    elcodi.location_manager.api.version: v1

    #
    # Location api routes
    #
    elcodi.route.location_api.host: 127.0.0.1:8000
    elcodi.route.location_api.prefix: /api/locations

    elcodi.route.location_api.get_root_locations: root
    elcodi.route.location_api.get_children: children
    elcodi.route.location_api.get_parents: parents
    elcodi.route.location_api.get_location: location
    elcodi.route.location_api.get_hierarchy: hierarchy
    elcodi.route.location_api.in: in

    #
    # Location provider active
    #
    elcodi.location_provider: "elcodi.location_provider.service"
