services:

    #
    # Repositories
    #

    #
    # Repository for entity country
    #
    elcodi.repository.country:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.geo.entity.country.class% ]

    #
    # Repository for entity state
    #
    elcodi.repository.state:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.geo.entity.state.class% ]

    #
    # Repository for entity province
    #
    elcodi.repository.province:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.geo.entity.province.class% ]

    #
    # Repository for entity city
    #
    elcodi.repository.city:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.geo.entity.city.class% ]

    #
    # Repository for entity postalcode
    #
    elcodi.repository.postal_code:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.geo.entity.postal_code.class% ]

    #
    # Repository for entity address
    #
    elcodi.repository.address:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.geo.entity.address.class% ]

    #
    # Repository for entity zone
    #
    elcodi.repository.zone:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.geo.entity.zone.class% ]

    #
    # Repository for entity zone member
    #
    elcodi.repository.zone_member:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.geo.entity.zone_member.class% ]

    #
    # Repository for entity zone country member
    #
    elcodi.repository.zone_country_member:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.geo.entity.zone_country_member.class% ]

    #
    # Repository for entity zone state member
    #
    elcodi.repository.zone_state_member:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.geo.entity.zone_state_member.class% ]

    #
    # Repository for entity zone province member
    #
    elcodi.repository.zone_province_member:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.geo.entity.zone_province_member.class% ]

    #
    # Repository for entity zone city member
    #
    elcodi.repository.zone_city_member:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.geo.entity.zone_city_member.class% ]

    #
    # Repository for entity zone postal code member
    #
    elcodi.repository.zone_postal_code_member:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.geo.entity.zone_postal_code_member.class% ]

    #
    # Repository for entity location
    #
    elcodi.repository.location:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.geo.entity.location.class% ]
