services:

    #
    # Transformers
    #
    elcodi.transformer.location_to_location_data:
        class: Elcodi\Component\Geo\Transformer\LocationToLocationDataTransformer
        arguments:
            - '@elcodi.factory.location_data'
