services:

    #
    # Object Managers
    #
    elcodi.object_manager.attribute:
        class: Doctrine\Common\Persistence\ObjectManager
        factory_service: elcodi.manager_provider
        factory_method: getManagerByEntityNamespace
        arguments:
            attribute_namespace: %elcodi.core.attribute.entity.attribute.class%

    elcodi.object_manager.attribute_value:
        class: Doctrine\Common\Persistence\ObjectManager
        factory_service: elcodi.manager_provider
        factory_method: getManagerByEntityNamespace
        arguments:
            value_namespace: %elcodi.core.attribute.entity.attribute_value.class%
