services:
    elcodi.core.currency.form_types.currency:
        class: %elcodi.core.currency.form_types.currency.class%
        tags:
            - { name: form.type, alias: elcodi_core_form_types_currency }