services:

    #
    # Event Listeners
    #
    elcodi.event_listener.product_category_integrity:
        class: Elcodi\Component\Product\EventListener\ProductCategoryIntegrityEventListener
        arguments:
            - @elcodi.service.category_integrity_fixer
        tags:
            - { name: doctrine.event_listener, event: onFlush, method: onFlush }

    elcodi.event_listener.root_category:
        class: Elcodi\Component\Product\EventListener\RootCategoryEventListener
        tags:
            - { name: doctrine.event_listener, event: preFlush, method: preFlush }
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
