services:

    #
    # Providers
    #
    elcodi.container_parameters:
        class: %elcodi.container_parameters.class%
        factory_service: service_container
        factory_method: getParameterBag

    elcodi.core.core.service.manager_provider:
        class: %elcodi.core.core.service.manager_provider.class%
        arguments:
            manager: @doctrine
            parameters_bag: @elcodi.container_parameters

    elcodi.manager_provider:
        alias: elcodi.core.core.service.manager_provider

    elcodi.core.core.service.repository_provider:
        class: %elcodi.core.core.service.repository_provider.class%
        arguments:
            manager_provider: @elcodi.manager_provider
            parameters_bag: @elcodi.container_parameters

    elcodi.repository_provider:
        alias: elcodi.core.core.service.repository_provider
