services:

    #
    # Providers
    #
    elcodi.container_parameters:
        class: Symfony\Component\DependencyInjection\ParameterBag\ParameterBag
        factory:
            - '@service_container'
            - getParameterBag

    elcodi.provider.manager:
        class: Elcodi\Component\Core\Services\ManagerProvider
        arguments:
            - '@doctrine'
            - '@elcodi.container_parameters'

    elcodi.provider.repository:
        class: Elcodi\Component\Core\Services\RepositoryProvider
        arguments:
            - '@elcodi.provider.manager'
            - '@elcodi.container_parameters'

    elcodi.mapping_provider:
        class: Elcodi\Component\Core\Services\MappingProvider
        arguments:
            - %elcodi.mapping_implementations%

    elcodi.referrer_provider:
        class: Elcodi\Component\Core\Services\ReferrerProvider
        arguments:
            - '@session'
            - '@request_stack'
