parameters:

    #
    # Services
    #
    elcodi.coupon_manager.class: Elcodi\Component\Coupon\Services\CouponManager

    #
    # Factories
    #
    elcodi.factory.coupon.class: Elcodi\Component\Coupon\Factory\CouponFactory

    #
    # Event Dispatchers
    #
    elcodi.event_dispatchers.coupon.class: Elcodi\Component\Coupon\EventDispatcher\CouponEventDispatcher

    #
    # Event Listeners
    #
    elcodi.event_listener.make_coupon_used.class: Elcodi\Component\Coupon\EventListener\MakeCouponUsedEventListener
