services:

    #
    # Services
    #
    elcodi.manager.coupon:
        class: Elcodi\Component\Coupon\Services\CouponManager
        arguments:
            - '@elcodi.factory.coupon'
            - '@elcodi.generator.random_string'
            - '@elcodi.factory.datetime'
