parameters:

    #
    # Entities
    #
    elcodi.core.media.entity.image.class: Elcodi\MediaBundle\Entity\Image

    #
    # Service
    #
    elcodi.core.media.services.image_manager.class: Elcodi\MediaBundle\Services\ImageManager

    #
    # Factories
    #
    elcodi.core.media.factory.image.class: Elcodi\MediaBundle\Factory\ImageFactory

    #
    # Services
    #
    elcodi.core.media.resize.imagemagick.class: Elcodi\MediaBundle\Adapter\Resizer\ImageMagickResizeAdapter

    #
    # Controllers
    #
    elcodi.core.media.controllers.image_resize.class: Elcodi\MediaBundle\Controller\ImageResizeController
    elcodi.core.media.controllers.image_upload.class: Elcodi\MediaBundle\Controller\ImageUploadController

    #
    # Routes
    #
    elcodi.core.media.routes.image_resize.loader.class: Elcodi\MediaBundle\Router\ImageResizeRouterLoader
    elcodi.core.media.routes.image_upload.loader.class: Elcodi\MediaBundle\Router\ImageUploadRouterLoader

    #
    # Transformers
    #
    elcodi.core.media.transformer.file.class: Elcodi\MediaBundle\Transformer\FileTransformer