services:

    #
    # Service
    #
    elcodi.core.media.services.image_manager:
        class: %elcodi.core.media.services.image_manager.class%
        arguments:
            image_factory: @elcodi.core.media.factory.image

    elcodi.core.media.services.file_manager:
        class: %elcodi.core.media.services.file_manager.class%
        arguments:
            filesystem: @elcodi.core.media.filesystem.default
            file_transformer: @elcodi.core.media.transformer.file

    #
    # Resize
    #
    elcodi.core.media.resize.imagemagick:
        class: %elcodi.core.media.resize.imagemagick.class%
        arguments:
            image_converter_bin_path: %elcodi.core.media.image_resize_converter_bin_path%
            image_converter_default_profile: %elcodi.core.media.image_resize_converter_default_profile%

    #
    # Routes
    #
    elcodi.core.media.routes.image_resize.loader:
        class: %elcodi.core.media.routes.image_resize.loader.class%
        arguments:
            image_resize_controller_route_name: %elcodi.core.media.image_resize_controller_route_name%
            image_resize_controller_route: %elcodi.core.media.image_resize_controller_route%
        tags:
            - { name: routing.loader }

    elcodi.core.media.routes.image_upload.loader:
        class: %elcodi.core.media.routes.image_upload.loader.class%
        arguments:
            image_upload_controller_route_name: %elcodi.core.media.image_upload_controller_route_name%
            image_upload_controller_route: %elcodi.core.media.image_upload_controller_route%
        tags:
            - { name: routing.loader }

    #
    # Transformers
    #
    elcodi.core.media.transformer.file:
        class: %elcodi.core.media.transformer.file.class%