doctrine_cache:
    providers:

        #
        # Categories cache
        #
        elcodi_categories:
            type: redis
            namespace: categories

        #
        # Menus cache
        #
        elcodi_menus:
            type: redis
            namespace: menus

        #
        # Configuration values cache
        #
        elcodi_configurations:
            type: redis
            namespace: configuration

        #
        # Entity translations cache
        #
        elcodi_translations:
            type: redis
            namespace: translations

        #
        # Comments cache
        #
        elcodi_comments:
            type: redis
            namespace: comments
