elcodi_configuration:
    elements:

        #
        # Store namespace
        #
        store_name:
            key: name
            name: Store name
            namespace: store
            type: string
            can_be_empty: false
            reference: elcodi.core.bamboo.store_name

        store_leitmotiv:
            key: leitmotiv
            name: Store leitmotiv
            namespace: store
            type: string
            can_be_empty: true

        store_phone:
            key: phone
            name: Store phone
            namespace: store
            type: string
            can_be_empty: true

        store_email:
            key: email
            name: Store email
            namespace: store
            type: string
            can_be_empty: true

        store_slug:
            key: slug
            name: Store slug
            namespace: store
            type: string
            can_be_empty: false
            reference: elcodi.core.bamboo.store_slug

        store_tracker:
            key: tracker
            name: Store tracker
            namespace: store
            type: string
            reference: elcodi.core.bamboo.store_tracker
            can_be_empty: false
            read_only: true

        store_template:
            key: template
            name: Store template
            namespace: store
            type: string
            can_be_empty: false
            empty_message: Template not enabled.

        store_templates:
            key: templates
            name: Store templates
            namespace: store
            type: array
            can_be_empty: false
            empty_message: Templates not loaded. Please, run "php app/console elcodi:templates:load"

        store_plugins:
            key: plugins
            name: Store plugins
            namespace: store
            type: array
            can_be_empty: true
            default_value: []

        store_enabled:
            key: enabled
            name: Store is enabled
            namespace: store
            type: boolean
            reference: elcodi.core.bamboo.store_enabled

        store_under_construction:
            key: under_construction
            name: Store is under construction
            namespace: store
            type: boolean
            reference: elcodi.core.bamboo.store_under_construction

        store_custom_domain:
            key: custom_domain
            name: Custom domain
            namespace: store
            type: string
            default_value: ''

        #
        # Product namespace
        #
        product_use_stock:
            key: use_stock
            name: Use Stock
            namespace: product
            type: boolean
            reference: elcodi.core.product.use_stock
            default_value: true

        #
        # Currency namespace
        #
        currency_default_currency:
            key: default_currency
            name: Default Currency
            namespace: currency
            type: string
            reference: elcodi.core.currency.default_currency
            read_only: false
