elcodi_configuration:
    elements:

        #
        # Store namespace
        store_name:
            key: name
            name: Store name
            namespace: store
            type: string
            reference: elcodi.core.bamboo.store_name

        store_tracker:
            key: tracker
            name: Store tracker
            namespace: store
            type: string
            reference: elcodi.core.bamboo.store_tracker

        store_template:
            key: template
            name: Store template
            namespace: store
            type: string
            reference: elcodi.core.bamboo.store_template

        store_templates:
            key: templates
            name: Store templates
            namespace: store
            type: array
            reference: elcodi.core.bamboo.store_templates

        #
        # Product namespace
        #
        product_use_stock:
            key: use_stock
            name: Use Stock
            namespace: product
            type: boolean
            reference: elcodi.core.product.use_stock

        #
        # Currency namespace
        #
        currency_default_currency:
            key: default_currency
            name: Default Currency
            namespace: currency
            type: string
            reference: elcodi.core.currency.default_currency
