services:

    #
    # Factories
    #

    #
    # Factory for entity banner
    #
    elcodi.factory.banner:
        class: Elcodi\Component\Banner\Factory\BannerFactory
        calls:
            - [setEntityNamespace, ["%elcodi.entity.banner.class%"]]
            - [setDateTimeFactory, ["@elcodi.factory.datetime"]]

    #
    # Factory for entity banner_zone
    #
    elcodi.factory.banner_zone:
        class: Elcodi\Component\Banner\Factory\BannerZoneFactory
        calls:
            - [setEntityNamespace, ["%elcodi.entity.banner_zone.class%"]]
