Elcodi\Component\User\Entity\Customer:
    type: entity
    repositoryClass: Elcodi\Component\User\Repository\CustomerRepository
    table: customer
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        phone:
            column: phone
            type: string
            length: 15
            nullable: true
        identityDocument:
            column: identity_document
            type: string
            length: 255
            nullable: true
        guest:
            column: guest
            type: boolean
        newsletter:
            column: newsletter
            type: boolean

    oneToMany:
        carts:
            targetEntity: Elcodi\Component\Cart\Entity\Interfaces\CartInterface
            mappedBy: customer
            orderBy:
                createdAt: DESC
            cascade: [ "persist" ]

        orders:
            targetEntity: Elcodi\Component\Cart\Entity\Interfaces\OrderInterface
            mappedBy: customer
            orderBy:
                createdAt: DESC
            cascade: [ "persist" ]

    oneToOne:
        deliveryAddress:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\AddressInterface
            joinColumn:
                name: delivery_address_id
                referencedColumnName: id
                nullable: true
                onDelete: "SET NULL"
            cascade: [ "persist" ]

        invoiceAddress:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\AddressInterface
            joinColumn:
                name: invoice_address_id
                referencedColumnName: id
                nullable: true
                onDelete: "SET NULL"
            cascade: [ "persist" ]

    manyToOne:
        language:
            targetEntity: Elcodi\Component\Language\Entity\Interfaces\LanguageInterface
            joinColumn:
                name: language_iso
                referencedColumnName: iso
                nullable: true

    manyToMany:
        addresses:
            targetEntity: Elcodi\Component\Geo\Entity\Interfaces\AddressInterface
            joinTable:
                name: customer_address
                joinColumns:
                    customer_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    address_id:
                        referencedColumnName: id

    lifecycleCallbacks:
            preUpdate: [loadUpdateAt]
            prePersist: [loadUpdateAt]
