parameters:

    #
    # Entities
    #
    elcodi.entity.state_transition_machine.state_line.class: Elcodi\Component\StateTransitionMachine\Entity\StateLine

    #
    # Factories
    #
    elcodi.factory.state_transition_machine.class: Elcodi\Component\StateTransitionMachine\Factory\MachineFactory
    elcodi.factory.state_transition_machine_state_line.class: Elcodi\Component\StateTransitionMachine\Factory\StateLineFactory

    #
    # Services
    #
    elcodi.state_transition_machine.loggable_machine.class: Elcodi\Component\StateTransitionMachine\Machine\LoggableMachine
    elcodi.state_transition_machine.machine_builder.class: Elcodi\Component\StateTransitionMachine\Machine\MachineBuilder
    elcodi.state_transition_machine.machine_manager.class: Elcodi\Component\StateTransitionMachine\Machine\MachineManager
    elcodi.state_transition_machine.machine.class: Elcodi\Component\StateTransitionMachine\Machine\Machine
