services:

    #
    # Factories
    #
    elcodi.factory.state_transition_machine:
        class: %elcodi.factory.state_transition_machine.class%

    elcodi.factory.state_transition_machine_state_line:
        class: %elcodi.factory.state_transition_machine_state_line.class%
        calls:
            - [setEntityNamespace, ["%elcodi.entity.state_transition_machine.state_line.class%"]]
