services:

    #
    # Factories
    #
    elcodi.factory.state_transition_machine:
        class: Elcodi\Component\StateTransitionMachine\Factory\MachineFactory

    elcodi.factory.state_transition_machine_state_line:
        class: Elcodi\Component\StateTransitionMachine\Factory\StateLineFactory
        calls:
            - [setEntityNamespace, ["%elcodi.entity.state_transition_machine.state_line.class%"]]
            - [setDateTimeFactory, ["@elcodi.factory.datetime"]]
