parameters:

    #
    # Entities
    #
    elcodi.core.language.entity.locale.class: Elcodi\Component\Language\Entity\Locale

    #
    # Factories
    #
    elcodi.core.language.factory.language.class: Elcodi\Component\Language\Factory\LanguageFactory

    #
    # Services
    #
    elcodi.core.language.service.language_manager.class: Elcodi\Component\Language\Services\LanguageManager
    elcodi.core.language.service.locale_manager.class: Elcodi\Component\Language\Services\LocaleManager
    elcodi.core.language.service.locale_provider.class: Elcodi\Component\Language\Services\LocaleProvider
