services:

    #
    # Twig extensions
    #
    elcodi.twig_extension.language:
        class: Elcodi\Component\Language\Twig\LanguageExtension
        arguments:
            - '@elcodi.manager.promoted_language'
        tags:
            - { name: twig.extension }
