services:

    #
    # Services
    #
    elcodi.core.cart.services.cart_manager:
        class: %elcodi.core.cart.services.cart_manager.class%
        arguments:
            entity_manager: @doctrine.orm.entity_manager
            event_dispatcher: @event_dispatcher
            cart_factory: @elcodi.core.cart.factory.cart
            cart_line_factory: @elcodi.core.cart.factory.cart_line

    elcodi.core.cart.services.order_manager:
        class: %elcodi.core.cart.services.order_manager.class%
        arguments:
        arguments:
            entity_manager: @doctrine.orm.entity_manager
            event_dispatcher: @event_dispatcher
            order_line_manager: @elcodi.core.cart.services.order_line_manager
            order_repository: @=service("doctrine.orm.entity_manager").getRepository("ElcodiCartBundle:Order")
            order_factory: @elcodi.core.cart.factory.order
            order_history_states: %elcodi.core.cart.order_states%

    elcodi.core.cart.services.order_line_manager:
        class: %elcodi.core.cart.services.order_line_manager.class%
        arguments:
            entity_manager: @doctrine.orm.entity_manager
            event_dispatcher: @event_dispatcher
            order_line_history_factory: @elcodi.core.cart.factory.order_line_history
            order_line_factory: @elcodi.core.cart.factory.order_line
            order_history_states: %elcodi.core.cart.order_states%
