services:

    #
    # Twig extensions
    #
    elcodi.twig_extension.menu_print_route:
        class: Elcodi\Component\Menu\Twig\PrintRouteExtension
        arguments:
            - '@router'
        tags:
            - { name: twig.extension }
