services:

    #
    # Twig extensions
    #
    elcodi.twig_extension.menu_print_route:
        class: %elcodi.twig_extension.menu_print_route.class%
        arguments:
            - @router
        tags:
            - { name: twig.extension }
