services:

    #
    # Services
    #
    elcodi.manager.plugin:
        class: Elcodi\Component\Plugin\Services\PluginManager
        arguments:
            - '@kernel'
            - '@elcodi.repository.plugin'
            - '@elcodi.object_manager.plugin'
            - '@elcodi.loader.plugin'

    elcodi.loader.plugin:
        class: Elcodi\Component\Plugin\Services\PluginLoader

    #
    # Router loader
    #
    elcodi.loader.plugin_routes:
        class: Elcodi\Component\Plugin\Loader\RouterLoader
        arguments:
            - '@kernel'
            - '@elcodi.plugins'
        tags:
            - { name: routing.loader }

    #
    # Aliases
    #
    elcodi.enabled_plugins:
        class: StdClass
        factory:
            - '@elcodi.repository.plugin'
            - findBy
        arguments:
            - {enabled: true}

    elcodi.plugins:
        class: StdClass
        factory:
            - '@elcodi.repository.plugin'
            - findAll

    elcodi.abstract_plugin:
        abstract: true
        class: Elcodi\Component\Plugin\Entity\Plugin
        factory:
            - '@elcodi.repository.plugin'
            - find
