services:

    #
    # Twig extensions
    #
    elcodi.twig_extension.plugin_hook:
        class: Elcodi\Component\Plugin\Twig\HookExtension
        public: false
        arguments:
            - '@elcodi.event_dispatcher.hook_system'
        tags:
            - { name: twig.extension }
