services:

    #
    # Wrappers
    #
    elcodi.wrapper.payment_methods:
        class: Elcodi\Component\Payment\Wrapper\PaymentWrapper
        arguments:
            - '@elcodi.event_dispatcher.payment'
