parameters:

    #
    # Factories
    #
    elcodi.factory.cart_coupon.class: Elcodi\Component\CartCoupon\Factory\CartCouponFactory
    elcodi.factory.order_coupon.class: Elcodi\Component\CartCoupon\Factory\OrderCouponFactory

    #
    # Event Listeners
    #
    elcodi.core.cart_coupon.event_listener.cart.class: Elcodi\Component\CartCoupon\EventListener\CartEventListener
    elcodi.core.cart_coupon.event_listener.order.class: Elcodi\Component\CartCoupon\EventListener\OrderEventListener
    elcodi.core.cart_coupon.event_listener.check_coupon.class: Elcodi\Component\CartCoupon\EventListener\CheckCouponEventListener
    elcodi.core.cart_coupon.event_listener.cart_coupon.class: Elcodi\Component\CartCoupon\EventListener\CartCouponEventListener
    elcodi.core.cart_coupon.event_listener.cart_coupon_rules.class: Elcodi\Component\CartCoupon\EventListener\CartCouponRulesEventListener
    elcodi.core.cart_coupon.event_listener.order_coupon.class: Elcodi\Component\CartCoupon\EventListener\OrderCouponEventListener
    elcodi.core.cart_coupon.event_listener.automatic_coupons.class: Elcodi\Component\CartCoupon\EventListener\AutomaticCouponApplicatorListener
    elcodi.core.cart_coupon.event_listener.duplicated_coupons.class: Elcodi\Component\CartCoupon\EventListener\CartCouponDuplicateListener

    #
    # Services
    #
    elcodi.cart_coupon_manager.class: Elcodi\Component\CartCoupon\Services\CartCouponManager
    elcodi.cart_coupon_rule_manager.class: Elcodi\Component\CartCoupon\Services\CartCouponRuleManager
    elcodi.order_coupon_manager.class: Elcodi\Component\CartCoupon\Services\OrderCouponManager

    #
    # EventDispatchers
    #
    elcodi.event_dispatcher.cart_coupon.class: Elcodi\Component\CartCoupon\EventDispatcher\CartCouponEventDispatcher
    elcodi.event_dispatcher.order_coupon.class: Elcodi\Component\CartCoupon\EventDispatcher\OrderCouponEventDispatcher
