parameters:

    #
    # Factories
    #
    elcodi.factory.cart_coupon.class: Elcodi\Component\CartCoupon\Factory\CartCouponFactory
    elcodi.factory.order_coupon.class: Elcodi\Component\CartCoupon\Factory\OrderCouponFactory

    #
    # Event Listeners
    #
    elcodi.event_listener.cart_coupon.refresh_coupons.class: Elcodi\Component\CartCoupon\EventListener\RefreshCouponsListener
    elcodi.event_listener.cart_coupon.coupon_checker.class: Elcodi\Component\CartCoupon\EventListener\CheckCouponListener
    elcodi.event_listener.cart_coupon.check_minimum_price.class: Elcodi\Component\CartCoupon\EventListener\MinimumPriceCouponEventListener
    elcodi.event_listener.cart_coupon.convert_to_order.class: Elcodi\Component\CartCoupon\EventListener\ConvertToOrderCouponsListener
    elcodi.event_listener.cart_coupon.cart_coupon_manager.class: Elcodi\Component\CartCoupon\EventListener\CartCouponManagerListener
    elcodi.event_listener.cart_coupon.check_rules.class: Elcodi\Component\CartCoupon\EventListener\CartCouponRulesEventListener
    elcodi.event_listener.cart_coupon.order_coupon_manager.class: Elcodi\Component\CartCoupon\EventListener\OrderCouponManagerListener
    elcodi.event_listener.cart_coupon.automatic_coupons.class: Elcodi\Component\CartCoupon\EventListener\AutomaticCouponApplicatorListener
    elcodi.event_listener.cart_coupon.avoid_coupon_duplicates.class: Elcodi\Component\CartCoupon\EventListener\AvoidDuplicatesListener
    elcodi.event_listener.cart_coupon.cart_coupon_checker.class: Elcodi\Component\CartCoupon\EventListener\CheckCartCouponListener

    #
    # Services
    #
    elcodi.manager.cart_coupon.class: Elcodi\Component\CartCoupon\Services\CartCouponManager
    elcodi.manager.cart_coupon_rule.class: Elcodi\Component\CartCoupon\Services\CartCouponRuleManager
    elcodi.manager.order_coupon.class: Elcodi\Component\CartCoupon\Services\OrderCouponManager

    #
    # EventDispatchers
    #
    elcodi.event_dispatcher.cart_coupon.class: Elcodi\Component\CartCoupon\EventDispatcher\CartCouponEventDispatcher
    elcodi.event_dispatcher.order_coupon.class: Elcodi\Component\CartCoupon\EventDispatcher\OrderCouponEventDispatcher
