services:

    #
    # Event Listeners
    #
    elcodi.core.cart_coupon.event_listener.cart:
        class: %elcodi.core.cart_coupon.event_listener.cart.class%
        arguments:
            coupon_manager: @elcodi.core.coupon.service.coupon_manager
            cart_coupon_manager: @elcodi.core.cart_coupon.service.cart_coupon_manager
            currency_wrapper: @elcodi.currency_wrapper
            currency_converter: @elcodi.currency_converter
            cart_coupon_rule_manager: @elcodi.cart_coupon_rule_manager
            cart_coupon_event_dispatcher: @elcodi.cart_coupon_event_dispatcher
        tags:
            - { name: kernel.event_listener, event: cart.preload, method: onCartPreLoadCoupons, priority: 0 }
            - { name: kernel.event_listener, event: cart.onload, method: onCartLoadCoupons, priority: -32 }

    elcodi.core.cart_coupon.event_listener.order:
        class: %elcodi.core.cart_coupon.event_listener.order.class%
        arguments:
            order_coupon_event_dispatcher: @elcodi.order_coupon_event_dispatcher
            cart_coupon_manager: @elcodi.cart_coupon_manager
            order_coupon_manager: @elcodi.order_coupon_manager
            order_coupon_object_manager: @elcodi.object_manager.order_coupon
        tags:
            - { name: kernel.event_listener, event: order.oncreated, method: onOrderOnCreatedEvent, priority: -16 }

    elcodi.core.cart_coupon.event_listener.cart_coupon:
        class: %elcodi.core.cart_coupon.event_listener.cart_coupon.class%
        arguments:
            cart_coupon_object_manager: @elcodi.object_manager.cart_coupon
            cart_coupon_factory: @elcodi.factory.cart_coupon
        tags:
            - { name: kernel.event_listener, event: cart_coupon.onapply, method: onCartCouponApply, priority: 0 }
            - { name: kernel.event_listener, event: cart_coupon.onremove, method: onCartCouponRemove, priority: 0 }

    elcodi.core.cart_coupon.event_listener.cart_coupon_rules:
        class: %elcodi.core.cart_coupon.event_listener.cart_coupon_rules.class%
        arguments:
            cart_coupon_rule_manager: @elcodi.cart_coupon_rule_manager
            cart_coupon_event_dispatcher: @elcodi.cart_coupon_event_dispatcher
        tags:
            - { name: kernel.event_listener, event: cart_coupon.onapply, method: onCartCouponApply, priority: 16 }

    elcodi.core.cart_coupon.event_listener.order_coupon:
        class: %elcodi.core.cart_coupon.event_listener.order_coupon.class%
        arguments:
            order_coupon_object_manager: @elcodi.object_manager.order_coupon
            coupon_event_dispatcher: @elcodi.coupon_event_dispatcher
            order_coupon_factory: @elcodi.factory.order_coupon
        tags:
            - { name: kernel.event_listener, event: order_coupon.onapply, method: onOrderCouponApply, priority: 0 }

    elcodi.core.cart_coupon.event_listener.automatic_coupons:
        class: %elcodi.core.cart_coupon.event_listener.automatic_coupons.class%
        arguments:
            - @elcodi.cart_coupon_manager
            - @elcodi.repository.coupon
        tags:
            - { name: kernel.event_listener, event: cart.onload, method: tryAutomaticCoupons, priority: -16 }
