services:

    #
    # Factories
    #

    #
    # Factory for entity cart_coupon
    #
    elcodi.factory.cart_coupon:
        class: %elcodi.factory.cart_coupon.class%
        calls:
            - [setEntityNamespace, ["%elcodi.entity.cart_coupon.class%"]]

    #
    # Factory for entity order_coupon
    #
    elcodi.factory.order_coupon:
        class: %elcodi.factory.order_coupon.class%
        calls:
            - [setEntityNamespace, ["%elcodi.entity.order_coupon.class%"]]
