services:

    #
    # Services
    #
    elcodi.core.newsletter.service.newsletter_manager:
        class: %elcodi.core.newsletter.service.newsletter_manager.class%
        arguments:
            event_dispatcher: @event_dispatcher
            entity_manager: @doctrine.orm.entity_manager
            validator: @validator
            newsletter_subscription_factory: @elcodi.core.newsletter.factory.newsletter_subscription
            newsletter_subscription_repository: @=service("doctrine.orm.entity_manager").getRepository(parameter("elcodi.core.newsletter.entity.newsletter_subscription.class"))
            hash_generator: @elcodi.core.core.generator.sha1
