Elcodi\Component\Tax\Entity\Tax:
    type: entity
    repositoryClass: Elcodi\Component\Tax\Repository\TaxRepository
    table: tax
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            length: 15
            nullable: false
        description:
            column: description
            type: string
            length: 255
            nullable: false
        value:
            column: value
            type: float
        enabled:
            column: enabled
            type: boolean

    manyToOne:
        taxGroup:
            targetEntity: Elcodi\Component\Tax\Entity\Interfaces\TaxGroupInterface
            inversedBy: taxes
            joinColumn:
                name: tax_group_id
                referencedColumnName: id
                nullable: true
