Elcodi\Component\Cart\Entity\Order:
    type: entity
    repositoryClass: Elcodi\Component\Cart\Repository\OrderRepository
    table: orders
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        quantity:
            column: quantity
            type: integer
        productAmount:
            column: product_amount
            type: integer
            nullable: false
        couponAmount:
            column: coupon_amount
            type: integer
            nullable: true
        amount:
            column: amount
            type: integer
            nullable: false
        height:
            column: height
            type: integer
            nullable: false
        width:
            column: width
            type: integer
            nullable: false
        depth:
            column: depth
            type: integer
            nullable: false
        weight:
            column: weight
            type: integer
            nullable: false
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime

    oneToOne:
        cart:
            targetEntity: Elcodi\Component\Cart\Entity\Interfaces\CartInterface
            inversedBy: order
            joinColumn:
                name: cart_id
                referencedColumnName: id
                onDelete: "SET NULL"
                onUpdate: "CASCADE"
                nullable: true
        lastStateLine:
            targetEntity: Elcodi\Component\Cart\Entity\Interfaces\OrderStateLineInterface
            joinColumn:
                name: last_state_line_id
                referencedColumnName: id
                nullable: true

    manyToOne:
        customer:
            targetEntity: Elcodi\Component\User\Entity\Interfaces\CustomerInterface
            inversedBy: orders
            joinColumn:
                name: customer_id
                referencedColumnName: id
                nullable: true
                onDelete: "SET NULL"
        currency:
            targetEntity: Elcodi\Component\Currency\Entity\Interfaces\CurrencyInterface
            joinColumn:
                 name: currency_iso
                 referencedColumnName: iso
                 nullable: false
        productCurrency:
            targetEntity: Elcodi\Component\Currency\Entity\Interfaces\CurrencyInterface
            joinColumn:
                 name: product_currency_iso
                 referencedColumnName: iso
                 nullable: false
        couponCurrency:
            targetEntity: Elcodi\Component\Currency\Entity\Interfaces\CurrencyInterface
            joinColumn:
                 name: coupon_currency_iso
                 referencedColumnName: iso
                 nullable: true
    oneToMany:
        orderLines:
            targetEntity: Elcodi\Component\Cart\Entity\Interfaces\OrderLineInterface
            mappedBy: order
            cascade: [ "all" ]
            orphanRemoval: true
        stateLines:
            targetEntity: Elcodi\Component\Cart\Entity\Interfaces\OrderStateLineInterface
            mappedBy: order
            cascade: [ "all" ]
            orphanRemoval: true

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
