services:

    #
    # Factories
    #

    #
    # Factory for entity carrier
    #
    elcodi.factory.carrier:
        class: %elcodi.factory.carrier.class%
        calls:
            - [setEntityNamespace, ["%elcodi.entity.carrier.class%"]]

    #
    # Factory for entity shipping_weight_range
    #
    elcodi.factory.shipping_range:
        class: %elcodi.factory.shipping_range.class%
        arguments:
            - @elcodi.wrapper.currency
        calls:
            - [setEntityNamespace, ["%elcodi.entity.shipping_range.class%"]]

    #
    # Factory for entity shipping_weight_range
    #
    elcodi.factory.warehouse:
        class: %elcodi.factory.warehouse.class%
        calls:
            - [setEntityNamespace, ["%elcodi.entity.warehouse.class%"]]
