services:

    #
    # Object Managers
    #
    elcodi.object_manager.shipping_range:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.entity.shipping_range.class% ]

    elcodi.object_manager.carrier:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.entity.carrier.class% ]
