services:

    #
    # Repositories
    #

    #
    # Repository for entity shipping_range
    #
    elcodi.repository.shipping_range:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.entity.shipping_range.class% ]

    #
    # Repository for entity carrier
    #
    elcodi.repository.carrier:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.entity.carrier.class% ]
