services:

    #
    # Repositories
    #

    #
    # Repository for entity carrier_base_range
    #
    elcodi.core.shipping.repository.carrier_base_range:
        class: %elcodi.core.shipping.repository.carrier_base_range.class%
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.shipping.entity.carrier_base_range.class%

    elcodi.repository.carrier_base_range:
        alias: elcodi.core.shipping.repository.carrier_base_range

    #
    # Repository for entity carrier_price_range
    #
    elcodi.core.shipping.repository.carrier_price_range:
        class: %elcodi.core.shipping.repository.carrier_price_range.class%
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.shipping.entity.carrier_price_range.class%

    elcodi.repository.carrier_price_range:
        alias: elcodi.core.shipping.repository.carrier_price_range

    #
    # Repository for entity carrier_weight_range
    #
    elcodi.core.shipping.repository.carrier_weight_range:
        class: %elcodi.core.shipping.repository.carrier_weight_range.class%
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.shipping.entity.carrier_weight_range.class%

    elcodi.repository.carrier_weight_range:
        alias: elcodi.core.shipping.repository.carrier_weight_range

    #
    # Repository for entity carrier
    #
    elcodi.core.shipping.repository.carrier:
        class: %elcodi.core.shipping.repository.carrier.class%
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.shipping.entity.carrier.class%

    elcodi.repository.carrier:
        alias: elcodi.core.shipping.repository.carrier

    #
    # Repository for entity warehouse
    #
    elcodi.core.shipping.repository.warehouse:
        class: %elcodi.core.shipping.repository.warehouse.class%
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.shipping.entity.warehouse.class%

    elcodi.repository.warehouse:
        alias: elcodi.core.shipping.repository.warehouse
