services:

    #
    # Wrappers
    #
    elcodi.wrapper.shipping_methods:
        class: Elcodi\Component\Shipping\Wrapper\ShippingWrapper
        arguments:
            - '@elcodi.event_dispatcher.shipping'
