Elcodi\CartBundle\Entity\Cart:
    type: entity
    repositoryClass: Elcodi\CartBundle\Repository\CartRepository
    table: cart
    fields:
        quantity:
            column: quantity
            type: integer
        productAmount:
            column: product_amount
            type: integer
            nullable: false
        couponAmount:
            column: coupon_amount
            type: integer
            nullable: true
        amount:
            column: amount
            type: integer
            nullable: false
        ordered:
            column: ordered
            type: boolean
            nullable: false
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime

    oneToOne:
        order:
            targetEntity: Elcodi\CartBundle\Entity\Interfaces\OrderInterface
            mappedBy: cart

    manyToOne:
        customer:
            targetEntity: Elcodi\UserBundle\Entity\Customer
            inversedBy: carts
            joinColumn:
                name: customer_id
                referencedColumnName: id
                nullable: true
        currency:
            targetEntity: Elcodi\CurrencyBundle\Entity\Interfaces\CurrencyInterface
            joinColumn:
                 name: currency_id
                 referencedColumnName: id
                 nullable: false

    oneToMany:
        cartLines:
            targetEntity: Elcodi\CartBundle\Entity\Interfaces\CartLineInterface
            mappedBy: cart
            cascade: ["all"]

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
