Elcodi\CartBundle\Entity\Cart:
    type: entity
    repositoryClass: Elcodi\CartBundle\Repository\CartRepository
    table: cart
    fields:
        quantity:
            column: quantity
            type: integer
        ordered:
            column: ordered
            type: boolean
            nullable: false
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime

    oneToOne:
        order:
            targetEntity: Elcodi\CartBundle\Entity\Interfaces\OrderInterface
            mappedBy: cart

    manyToOne:
        customer:
            targetEntity: Elcodi\UserBundle\Entity\Interfaces\CustomerInterface
            inversedBy: carts
            joinColumn:
                name: customer_id
                referencedColumnName: id
                nullable: true

    oneToMany:
        cartLines:
            targetEntity: Elcodi\CartBundle\Entity\Interfaces\CartLineInterface
            mappedBy: cart
            cascade: ["all"]
            orphanRemoval: true

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
