Elcodi\CartBundle\Entity\CartLine:
    type: entity
    repositoryClass: Elcodi\CartBundle\Repository\CartLineRepository
    table: cart_line
    fields:
        productAmount:
            column: product_amount
            type: integer
            nullable: false
        amount:
            column: amount
            type: integer
            nullable: false
        quantity:
            column: quantity
            type: integer

    manyToOne:
        cart:
            targetEntity: Elcodi\CartBundle\Entity\Interfaces\CartInterface
            inversedBy: cartLines
            joinColumn:
                name: cart_id
                referencedColumnName: id
                nullable: false
        productCurrency:
            targetEntity: Elcodi\CurrencyBundle\Entity\Interfaces\CurrencyInterface
            joinColumn:
                 name: product_currency_id
                 referencedColumnName: id
                 nullable: false
        currency:
            targetEntity: Elcodi\CurrencyBundle\Entity\Interfaces\CurrencyInterface
            joinColumn:
                 name: currency_id
                 referencedColumnName: id
                 nullable: false
        product:
            targetEntity: Elcodi\ProductBundle\Entity\Interfaces\ProductInterface
            joinColumn:
                name: product_id
                referencedColumnName: id
                nullable: false
        variant:
            targetEntity: Elcodi\ProductBundle\Entity\Interfaces\VariantInterface
            joinColumn:
                name: variant_id
                referencedColumnName: id
                nullable: true
