Elcodi\CartBundle\Entity\OrderLine:
    type: entity
    repositoryClass: Elcodi\CartBundle\Repository\OrderLineRepository
    table: order_line
    fields:
        productAmount:
            column: product_amount
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        amount:
            column: amount
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        quantity:
            column: quantity
            type: integer

    oneToOne:
        lastOrderLineHistory:
            targetEntity: Elcodi\CartBundle\Entity\Interfaces\OrderLineHistoryInterface
            joinColumn:
                name: last_order_line_history_id
                referencedColumnName: id
                nullable: true

    oneToMany:
        orderLineHistories:
            targetEntity: Elcodi\CartBundle\Entity\Interfaces\OrderLineHistoryInterface
            mappedBy: orderLine
            cascade: [ all ]
            orphanRemoval: true

    manyToOne:
        order:
            targetEntity: Elcodi\CartBundle\Entity\Interfaces\OrderInterface
            inversedBy: orderLines
            cascade: [ all ]
            joinColumn:
                name: order_id
                referencedColumnName: id
                nullable: false
        currency:
            targetEntity: Elcodi\CurrencyBundle\Entity\Interfaces\CurrencyInterface
            joinColumn:
                 name: currency_id
                 referencedColumnName: id
                 nullable: false
        product:
            targetEntity: Elcodi\ProductBundle\Entity\Interfaces\ProductInterface
            joinColumn:
                name: product_id
                referencedColumnName: id
                nullable: false
        variant:
            targetEntity: Elcodi\ProductBundle\Entity\Interfaces\VariantInterface
            joinColumn:
                name: variant_id
                referencedColumnName: id
                nullable: true
