Elcodi\MenuBundle\Entity\Menu\Menu:
    type: entity
    repositoryClass: Elcodi\MenuBundle\Repository\MenuRepository
    table: menu
    fields:
        code:
            column: code
            type: string
            length: 255
            nullable: false
        description:
            column: text
            nullable: false
        enabled:
            column: enabled
            type: boolean
            nullable: false
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime

    manyToMany:
        subnodes:
            targetEntity: Elcodi\MenuBundle\Entity\Menu\Interfaces\NodeInterface
            cascade: ["PERSIST"]
            joinTable:
                name: menu_node_hierachy
                joinColumns:
                    menu_node_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    menu_subnode_id:
                        referencedColumnName: id

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
