parameters:

    #
    # Entities
    #
    elcodi.core.cart_coupon.entity.cart_coupon.class: Elcodi\CartCouponBundle\Entity\CartCoupon
    elcodi.core.cart_coupon.entity.order_coupon.class: Elcodi\CartCouponBundle\Entity\OrderCoupon

    #
    # Repositories
    #
    elcodi.core.cart_coupon.repository.cart_coupon.class: Elcodi\CartCouponBundle\Repository\CartCouponRepository
    elcodi.core.cart_coupon.repository.order_coupon.class: Elcodi\CartCouponBundle\Repository\OrderCouponRepository

    #
    # Factories
    #
    elcodi.core.cart_coupon.factory.cart_coupon.class: Elcodi\CartCouponBundle\Factory\CartCouponFactory
    elcodi.core.cart_coupon.factory.order_coupon.class: Elcodi\CartCouponBundle\Factory\OrderCouponFactory

    #
    # Event Listeners
    #
    elcodi.core.cart_coupon.event_listener.cart.class: Elcodi\CartCouponBundle\EventListener\CartEventListener
    elcodi.core.cart_coupon.event_listener.order.class: Elcodi\CartCouponBundle\EventListener\OrderEventListener
    elcodi.core.cart_coupon.event_listener.cart_coupon.class: Elcodi\CartCouponBundle\EventListener\CartCouponEventListener
    elcodi.core.cart_coupon.event_listener.cart_coupon_rules.class: Elcodi\CartCouponBundle\EventListener\CartCouponRulesEventListener
    elcodi.core.cart_coupon.event_listener.order_coupon.class: Elcodi\CartCouponBundle\EventListener\OrderCouponEventListener

    #
    # Services
    #
    elcodi.core.cart_coupon.service.cart_coupon_manager.class: Elcodi\CartCouponBundle\Services\CartCouponManager
    elcodi.core.cart_coupon.service.cart_coupon_rule_manager.class: Elcodi\CartCouponBundle\Services\CartCouponRuleManager
    elcodi.core.cart_coupon.service.order_coupon_manager.class: Elcodi\CartCouponBundle\Services\OrderCouponManager

    #
    # EventDispatchers
    #
    elcodi.core.cart_coupon.event_dispatcher.cart_coupon.class: Elcodi\CartCouponBundle\EventDispatcher\CartCouponEventDispatcher
    elcodi.core.cart_coupon.event_dispatcher.order_coupon.class: Elcodi\CartCouponBundle\EventDispatcher\OrderCouponEventDispatcher
