services:

    #
    # Directors
    #
    elcodi.director.tax:
        class: Elcodi\Component\Core\Services\ObjectDirector
        lazy: true
        arguments:
            - '@elcodi.object_manager.tax'
            - '@elcodi.repository.tax'
            - '@elcodi.factory.tax'
